fixed fail on purpose

diff --git a/.github/workflows/dev-pull.yaml b/.github/workflows/dev-pull.yaml
--- a/.github/workflows/dev-pull.yaml
+++ b/.github/workflows/dev-pull.yaml
@@ -67,5 +67,5 @@ jobs:
       - name: frontend testing
         run: npm run test:frontend
 
-      - name: fail on purpose
-        run: exit 1
+      # - name: fail on purpose
+      #   run: exit 1
